title: Studentkjellernes personalforening
description: Samarbeidsforening for studentkjellerne ved Universitetet i Oslo. Samtlig betalt personell ved kjellerne er forbundet med oss.
locale: nb_NO

#defaults:
#  -
#    scope:
#      path: ""
#    values:
#      layout: "default"
